import { adminApi } from './admin-api-client.js';

const labels={
  'product.created':'Creó el producto','product.updated':'Actualizó el producto','product.status_changed':'Cambió el estado del producto','product.archived':'Archivó el producto','product.restored':'Restauró el producto','product.image_added':'Añadió una imagen','product.image_replaced':'Reemplazó la imagen','product.image_removed':'Eliminó la imagen','product.reordered':'Cambió el orden de productos','product.deleted_permanently':'Eliminó permanentemente el producto',
  'category.created':'Creó la categoría','category.updated':'Actualizó la categoría','category.status_changed':'Cambió el estado de la categoría','category.archived':'Archivó la categoría','category.restored':'Restauró la categoría','category.reordered':'Cambió el orden de categorías','category.deleted_permanently':'Eliminó permanentemente la categoría',
  'user.invited':'Creó una invitación local','user.updated':'Actualizó el usuario','user.role_changed':'Cambió el rol del usuario','user.publishing_mode_changed':'Cambió sus permisos de publicación','user.activated':'Activó el usuario','user.deactivated':'Desactivó el usuario','user.password_reset_requested':'Registró una solicitud de cambio de contraseña','user.deleted_permanently':'Eliminó permanentemente el usuario',
  'revision.submitted':'Envió una revisión','revision.approved':'Aprobó la revisión','revision.rejected':'Rechazó la revisión','revision.cancelled':'Canceló la revisión','revision.conflict':'Detectó un conflicto de versión',
};
const valueLabels={draft:'Borrador',published:'Publicado',sold_out:'Agotado',hidden:'Oculto',archived:'Archivado',active:'Activo',inactive:'Inactivo',review_required:'Requiere revisión',direct_publish:'Puede publicar sin revisión'};
function detail(metadata={}){if(metadata.changes){return Object.entries(metadata.changes).map(([field,change])=>`${field}: ${valueLabels[change.from]??change.from??'sin valor'} → ${valueLabels[change.to]??change.to??'sin valor'}`).join(' · ')}if(metadata.comment)return`Comentario: ${metadata.comment}`;if(metadata.changed_fields)return`Campos modificados: ${metadata.changed_fields.join(', ')}`;if(metadata.from_version)return`Versión ${metadata.from_version} → ${metadata.to_version}`;return''}
const root=document.querySelector('[data-history]');
if(root){let type=new URLSearchParams(location.search).get('type')||'product',timer;const entityId=new URLSearchParams(location.search).get('entityId'),list=root.querySelector('[data-history-list]'),search=root.querySelector('[data-history-search]'),message=root.querySelector('[data-history-message]');const load=async()=>{try{const params=new URLSearchParams({type,search:search.value});if(entityId)params.set('entityId',entityId);const rows=await adminApi(`/api/admin/history?${params}`);list.replaceChildren(...rows.map(row=>{const li=document.createElement('li');li.className='admin-history-item';const title=document.createElement('strong'),meta=document.createElement('p'),description=document.createElement('p');title.textContent=`${row.user_name??'Perfil eliminado'} · ${labels[row.action]??'Realizó un cambio'}`;meta.textContent=new Date(row.created_at).toLocaleString('es-CL');description.textContent=detail(row.metadata);if(!description.textContent)description.hidden=true;li.append(title,meta,description);return li}));message.textContent=`${rows.length} registros`}catch(error){message.textContent=error.message}};root.querySelectorAll('[data-history-type]').forEach(button=>button.addEventListener('click',()=>{type=button.dataset.historyType;root.querySelectorAll('[data-history-type]').forEach(item=>item.setAttribute('aria-selected',String(item===button)));load()}));search.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(load,250)});load()}
