import { randomUUID } from 'node:crypto';
import { AdminDataError } from './products.js';
import { diffFields, writeAudit } from './audit.js';

const statuses = ['active', 'hidden', 'archived'];
const fields = ['name', 'slug', 'description', 'status', 'displayOrder'];
const map = (r) => r && ({ id:r.id,name:r.name,slug:r.slug,description:r.description,status:r.status,displayOrder:r.display_order,imagePath:r.image_path,imageAlt:r.image_alt,productCount:r.product_count??0,createdAt:r.created_at,updatedAt:r.updated_at });
function validate(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new AdminDataError('VALIDATION_ERROR','Revisa la categoría.',400,{form:'JSON inválido.'});
  const unknown=Object.keys(input).filter(k=>!['name','slug','description','status','displayOrder','imageAlt'].includes(k));
  if(unknown.length) throw new AdminDataError('VALIDATION_ERROR','Campos no permitidos.',400,{form:unknown.join(', ')});
  const v={name:String(input.name??'').trim(),slug:String(input.slug??'').trim().toLowerCase(),description:String(input.description??'').trim()||null,status:input.status,displayOrder:Number(input.displayOrder),imageAlt:String(input.imageAlt??'').trim()||null}; const e={};
  if(v.name.length<2||v.name.length>50)e.name='Debe tener entre 2 y 50 caracteres.';
  if(v.slug.length<2||v.slug.length>80||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v.slug))e.slug='Slug URL-safe inválido.';
  if(v.description&&v.description.length>250)e.description='Máximo 250 caracteres.';
  if(!statuses.includes(v.status))e.status='Estado inválido.';
  if(!Number.isInteger(v.displayOrder)||v.displayOrder<0)e.displayOrder='Debe ser entero mayor o igual a 0.';
  if(v.imageAlt&&(v.imageAlt.length<5||v.imageAlt.length>180))e.imageAlt='Debe tener entre 5 y 180 caracteres.';
  if(Object.keys(e).length)throw new AdminDataError('VALIDATION_ERROR','Revisa los campos.',400,e); return v;
}

export class CategoryRepository {
  constructor(db){this.db=db;this.select=`SELECT categories.*, count(products.id) product_count FROM categories LEFT JOIN products ON products.category_id=categories.id`;}
  list(){return this.db.prepare(`${this.select} GROUP BY categories.id ORDER BY categories.display_order,categories.name`).all().map(map);}
  get(id){return map(this.db.prepare(`${this.select} WHERE categories.id=? GROUP BY categories.id`).get(id));}
  assertSlug(slug,exclude=null){const r=exclude?this.db.prepare('SELECT 1 FROM categories WHERE slug=? AND id<>?').get(slug,exclude):this.db.prepare('SELECT 1 FROM categories WHERE slug=?').get(slug);if(r)throw new AdminDataError('SLUG_EXISTS','Ya existe una categoría con ese slug.',409,{slug:'Este slug ya está en uso.'});}
  create(input,userId){const v=validate(input);this.assertSlug(v.slug);v.displayOrder=Math.min(v.displayOrder,this.db.prepare('SELECT count(*) total FROM categories').get().total);const id=randomUUID(),now=new Date().toISOString();this.db.transaction(()=>{this.db.prepare('UPDATE categories SET display_order=display_order+1 WHERE display_order>=?').run(v.displayOrder);this.db.prepare('INSERT INTO categories (id,name,slug,description,status,display_order,image_path,image_alt,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,NULL,?,?,?, ?,?)').run(id,v.name,v.slug,v.description,v.status,v.displayOrder,v.imageAlt,userId,userId,now,now);writeAudit(this.db,{userId,action:'category.created',entityType:'category',entityId:id,metadata:{snapshot:v}});})();return this.get(id);}
  update(id,input,userId){const before=this.get(id);if(!before)throw new AdminDataError('CATEGORY_NOT_FOUND','Categoría no encontrada.',404);const v=validate(input);this.assertSlug(v.slug,id);v.displayOrder=Math.min(v.displayOrder,Math.max(0,this.db.prepare('SELECT count(*) total FROM categories').get().total-1));const now=new Date().toISOString();this.db.transaction(()=>{if(v.displayOrder<before.displayOrder)this.db.prepare('UPDATE categories SET display_order=display_order+1 WHERE id<>? AND display_order>=? AND display_order<?').run(id,v.displayOrder,before.displayOrder);if(v.displayOrder>before.displayOrder)this.db.prepare('UPDATE categories SET display_order=display_order-1 WHERE id<>? AND display_order>? AND display_order<=?').run(id,before.displayOrder,v.displayOrder);this.db.prepare('UPDATE categories SET name=?,slug=?,description=?,status=?,display_order=?,image_alt=?,updated_by=?,updated_at=? WHERE id=?').run(v.name,v.slug,v.description,v.status,v.displayOrder,v.imageAlt,userId,now,id);const after=this.get(id),changes=diffFields(before,after,[...fields,'imageAlt']);writeAudit(this.db,{userId,action:changes.status?'category.status_changed':'category.updated',entityType:'category',entityId:id,metadata:{changes}});if(changes.displayOrder)writeAudit(this.db,{userId,action:'category.reordered',entityType:'category',entityId:id,metadata:{before:before.displayOrder,after:v.displayOrder}});})();return this.get(id);}
  status(id,status,userId){const before=this.get(id);if(!before)throw new AdminDataError('CATEGORY_NOT_FOUND','Categoría no encontrada.',404);const action=status==='archived'?'category.archived':'category.restored';this.db.transaction(()=>{this.db.prepare('UPDATE categories SET status=?,updated_by=?,updated_at=? WHERE id=?').run(status,userId,new Date().toISOString(),id);writeAudit(this.db,{userId,action,entityType:'category',entityId:id,metadata:{changes:{status:{from:before.status,to:status}}}});})();return this.get(id);}
  delete(id,resolution,userId){const source=this.get(id);if(!source)throw new AdminDataError('CATEGORY_NOT_FOUND','Categoría no encontrada.',404);if(source.status!=='archived')throw new AdminDataError('ARCHIVE_REQUIRED','Archiva la categoría antes de eliminarla.',409);return this.db.transaction(()=>{let targetId=null,action='category.products_unassigned';if(source.productCount){if(resolution?.mode==='move'){targetId=resolution.targetCategoryId;if(targetId===id||!this.get(targetId))throw new AdminDataError('CATEGORY_NOT_FOUND','Destino inválido.',400);action='category.products_moved';}else if(resolution?.mode==='create_and_move'){const created=this.create(resolution.category,userId);targetId=created.id;action='category.created_and_moved';}else if(resolution?.mode!=='unassign')throw new AdminDataError('RESOLUTION_REQUIRED','Debes resolver los productos de la categoría.',400);this.db.prepare('UPDATE products SET category_id=?,updated_by=?,updated_at=?,version=version+1 WHERE category_id=?').run(targetId,userId,new Date().toISOString(),id);}this.db.prepare('DELETE FROM categories WHERE id=?').run(id);writeAudit(this.db,{userId,action,entityType:'category',entityId:id,metadata:{snapshot:source,targetCategoryId:targetId}});writeAudit(this.db,{userId,action:'category.deleted_permanently',entityType:'category',entityId:id,metadata:{snapshot:source}});return {id};})();}
}

export class CategoryService {
 constructor(repo,profileService){this.repo=repo;this.profileService=profileService;}
 list(id){this.profileService.requireProfile(id);return this.repo.list();} get(x,id){this.profileService.requireProfile(id);const r=this.repo.get(x);if(!r)throw new AdminDataError('CATEGORY_NOT_FOUND','Categoría no encontrada.',404);return r;}
 create(v,id){this.profileService.requireProfile(id,{write:true});return this.repo.create(v,id);} update(x,v,id){this.profileService.requireProfile(id,{write:true});return this.repo.update(x,v,id);} archive(x,id){this.profileService.requireProfile(id,{write:true});return this.repo.status(x,'archived',id);} restore(x,id){this.profileService.requireProfile(id,{write:true});return this.repo.status(x,'active',id);} delete(x,v,id){this.profileService.requireProfile(id,{write:true});if(v?.reauth!=='DELETE DEV')throw new AdminDataError('DEV_REAUTH_REQUIRED','Confirmación DEV inválida.',403);return this.repo.delete(x,v.resolution,id);}
}
