import { randomUUID } from 'node:crypto';
import { AdminDataError } from './products.js';
import { diffFields, writeAudit } from './audit.js';
import { DevAccountNotificationService } from './notifications.js';

const ROLES = new Set(['editor', 'admin', 'developer']);
const MODES = new Set(['review_required', 'direct_publish']);
const mapUser = (row) => row && ({ id:row.id, displayName:row.display_name, username:row.username, email:row.email, role:row.role, publishingMode:row.publishing_mode, status:row.is_active?'active':'inactive', isActive:Boolean(row.is_active), invitationStatus:row.invitation_status, createdAt:row.created_at, updatedAt:row.updated_at });

function validate(input, invite = false) {
  if (!input || Object.keys(input).some((key) => !['displayName','username','email','role','publishingMode'].includes(key))) throw new AdminDataError('VALIDATION_ERROR','Datos de usuario inválidos.',400);
  const value={displayName:String(input.displayName??'').trim(),username:String(input.username??'').trim().toLowerCase(),email:String(input.email??'').trim().toLowerCase(),role:String(input.role??'editor'),publishingMode:String(input.publishingMode??'review_required')};
  const fields={};
  if(value.displayName.length<2||value.displayName.length>80)fields.displayName='Usa entre 2 y 80 caracteres.';
  if(!/^[a-z0-9_.-]{2,50}$/.test(value.username))fields.username='Username inválido.';
  if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.email)||value.email.length>254)fields.email='Email inválido.';
  if(!ROLES.has(value.role)||(invite&&value.role==='developer'))fields.role='Rol inválido para esta operación.';
  if(!MODES.has(value.publishingMode))fields.publishingMode='Modalidad inválida.';
  if(Object.keys(fields).length)throw new AdminDataError('VALIDATION_ERROR','Revisa los datos del usuario.',400,fields);
  if(value.role!=='editor')value.publishingMode='direct_publish';
  return value;
}

export class UserService {
  constructor(db,auth,notifications=new DevAccountNotificationService()){this.db=db;this.auth=auth;this.notifications=notifications}
  actor(id){const profile=this.auth.requireProfile(id);if(profile.role==='editor')throw new AdminDataError('USERS_FORBIDDEN','No tienes permiso para administrar usuarios.',403);return profile}
  raw(id){return this.db.prepare('SELECT * FROM profiles WHERE id=?').get(id)}
  target(actor,id,{selfData=false}={}){const row=this.raw(id);if(!row)throw new AdminDataError('USER_NOT_FOUND','Usuario no encontrado.',404);if(actor.role==='admin'&&row.role!=='editor'&&!(selfData&&row.id===actor.id))throw new AdminDataError('USER_FORBIDDEN','Admin sólo puede gestionar Editors.',403);return row}
  list(actorId,{search=''}={}){const actor=this.actor(actorId),q=`%${String(search).trim().toLowerCase()}%`;return this.db.prepare(`SELECT * FROM profiles WHERE (?='developer' OR role='editor') AND (?='%%' OR lower(display_name) LIKE ? OR lower(username) LIKE ? OR lower(email) LIKE ? OR lower(role) LIKE ?) ORDER BY display_name`).all(actor.role,q,q,q,q,q).map(mapUser)}
  get(id,actorId){return mapUser(this.target(this.actor(actorId),id,{selfData:true}))}
  unique(value,id=null){if(this.db.prepare('SELECT id FROM profiles WHERE (lower(username)=? OR lower(email)=?) AND (? IS NULL OR id<>?)').get(value.username,value.email,id,id))throw new AdminDataError('USER_EXISTS','El username o email ya está registrado.',409)}
  invite(input,actorId){const actor=this.actor(actorId),value=validate(input,true);if(actor.role==='admin'&&value.role!=='editor')throw new AdminDataError('ROLE_FORBIDDEN','Admin sólo puede invitar Editors.',403);this.unique(value);const id=randomUUID(),now=new Date().toISOString();this.db.transaction(()=>{this.db.prepare(`INSERT INTO profiles(id,username,display_name,email,role,publishing_mode,is_active,invitation_status,created_at,updated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,1,'pending',?,?,?,?)`).run(id,value.username,value.displayName,value.email,value.role,value.publishingMode,now,now,actorId,actorId);writeAudit(this.db,{userId:actorId,action:'user.invited',entityType:'profile',entityId:id,metadata:{snapshot:value,delivery:'not_sent'}})})();return{user:this.get(id,actorId),notification:this.notifications.sendInvitation()}}
  update(id,input,actorId){const actor=this.actor(actorId),before=this.target(actor,id,{selfData:true}),value=validate(input);if(before.id===actor.id&&(value.role!==before.role||value.publishingMode!==before.publishing_mode))throw new AdminDataError('SELF_PRIVILEGE_CHANGE','No puedes cambiar tus propios privilegios.',403);if(actor.role==='admin'&&(before.role!=='editor'||value.role!=='editor'))throw new AdminDataError('ROLE_FORBIDDEN','Admin sólo puede gestionar Editors.',403);if(value.role==='developer'&&before.role!=='developer')throw new AdminDataError('ROLE_FORBIDDEN','No se crean Developers desde este módulo.',403);if(before.role==='developer'&&value.role!=='developer')this.protectLastDeveloper(before);this.unique(value,id);this.db.transaction(()=>{this.db.prepare('UPDATE profiles SET display_name=?,username=?,email=?,role=?,publishing_mode=?,updated_at=?,updated_by=? WHERE id=?').run(value.displayName,value.username,value.email,value.role,value.publishingMode,new Date().toISOString(),actorId,id);const changes=diffFields(mapUser(before),mapUser(this.raw(id)),['displayName','username','email','role','publishingMode']);for(const key of ['role','publishingMode'])if(changes[key])writeAudit(this.db,{userId:actorId,action:key==='role'?'user.role_changed':'user.publishing_mode_changed',entityType:'profile',entityId:id,metadata:{changes:{[key]:changes[key]}}});const general=Object.fromEntries(Object.entries(changes).filter(([key])=>!['role','publishingMode'].includes(key)));if(Object.keys(general).length)writeAudit(this.db,{userId:actorId,action:'user.updated',entityType:'profile',entityId:id,metadata:{changes:general}})})();return this.get(id,actorId)}
  protectLastDeveloper(row){if(row.role==='developer'&&this.db.prepare("SELECT count(*) count FROM profiles WHERE role='developer' AND is_active=1").get().count<=1)throw new AdminDataError('LAST_DEVELOPER','No se puede afectar al último Developer activo.',409)}
  access(id,active,actorId){const actor=this.actor(actorId),row=this.target(actor,id);if(row.id===actor.id)throw new AdminDataError('SELF_ACCESS_CHANGE','No puedes cambiar tu propio acceso.',403);if(!active)this.protectLastDeveloper(row);this.db.transaction(()=>{this.db.prepare('UPDATE profiles SET is_active=?,updated_at=?,updated_by=? WHERE id=?').run(active?1:0,new Date().toISOString(),actorId,id);writeAudit(this.db,{userId:actorId,action:active?'user.activated':'user.deactivated',entityType:'profile',entityId:id,metadata:{changes:{status:{from:row.is_active?'active':'inactive',to:active?'active':'inactive'}}}})})();return mapUser(this.raw(id))}
  invitation(id,action,actorId){const actor=this.actor(actorId),row=this.target(actor,id),next=action==='cancel'?'cancelled':'pending';this.db.transaction(()=>{this.db.prepare('UPDATE profiles SET invitation_status=?,updated_at=?,updated_by=? WHERE id=?').run(next,new Date().toISOString(),actorId,id);writeAudit(this.db,{userId:actorId,action:action==='cancel'?'user.invitation_cancelled':'user.invitation_recreated',entityType:'profile',entityId:id,metadata:{changes:{invitationStatus:{from:row.invitation_status,to:next}},delivery:'not_sent'}})})();return{user:mapUser(this.raw(id)),notification:action==='recreate'?this.notifications.sendInvitation():{delivery:'not_sent',reason:'cancelled'}}}
  passwordReset(id,actorId){const actor=this.actor(actorId),row=this.target(actor,id);writeAudit(this.db,{userId:actorId,action:'user.password_reset_requested',entityType:'profile',entityId:id,metadata:{delivery:'not_sent',reason:'dev_environment'}});return{userId:row.id,notification:this.notifications.sendPasswordReset()}}
  delete(id,input,actorId){const actor=this.actor(actorId);if(actor.role!=='developer')throw new AdminDataError('DELETE_FORBIDDEN','Sólo Developer puede eliminar usuarios.',403);if(input?.reauth!=='DELETE DEV')throw new AdminDataError('DEV_REAUTH_REQUIRED','Confirmación DEV inválida.',403);const row=this.target(actor,id);if(row.is_active)throw new AdminDataError('INACTIVE_REQUIRED','Desactiva el usuario antes de eliminarlo.',409);this.protectLastDeveloper(row);const snapshot={id:row.id,displayName:row.display_name,username:row.username,email:row.email,role:row.role,status:'inactive'};this.db.transaction(()=>{writeAudit(this.db,{userId:actorId,action:'user.deleted_permanently',entityType:'profile',entityId:id,metadata:{snapshot}});this.db.prepare('DELETE FROM profiles WHERE id=?').run(id)})();return{id}}
}
